{
  "formatVersion": "1.1",
  "component": {
    "group": "com.linkcircle.fj",
    "module": "agorasignal",
    "version": "1.4.5.3",
    "attributes": {
      "org.gradle.status": "release"
    }
  },
  "createdBy": {
    "gradle": {
      "version": "7.4.2"
    }
  },
  "variants": [
    {
      "name": "releaseVariantReleaseApiPublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-api"
      },
      "files": [
        {
          "name": "agorasignal-1.4.5.3.aar",
          "url": "agorasignal-1.4.5.3.aar",
          "size": 16094428,
          "sha512": "7f5b441e65b2329d560b56de02898065e313034a855d266954e6cf9b6426cb6c5b5b3f68cb6fe811993d8e58a23c0573542f93a0d0dd46fe4f09a5bddf037462",
          "sha256": "0c6cd84a02145193da504b491bc580e5c57b8a460474c552319dfe9c929cc353",
          "sha1": "d91c0805cd455efe11399cf9fc58ba6f57138e6c",
          "md5": "3744304388911975a98bc8e1472ee5f7"
        }
      ]
    },
    {
      "name": "releaseVariantReleaseRuntimePublication",
      "attributes": {
        "org.gradle.category": "library",
        "org.gradle.dependency.bundling": "external",
        "org.gradle.libraryelements": "aar",
        "org.gradle.usage": "java-runtime"
      },
      "files": [
        {
          "name": "agorasignal-1.4.5.3.aar",
          "url": "agorasignal-1.4.5.3.aar",
          "size": 16094428,
          "sha512": "7f5b441e65b2329d560b56de02898065e313034a855d266954e6cf9b6426cb6c5b5b3f68cb6fe811993d8e58a23c0573542f93a0d0dd46fe4f09a5bddf037462",
          "sha256": "0c6cd84a02145193da504b491bc580e5c57b8a460474c552319dfe9c929cc353",
          "sha1": "d91c0805cd455efe11399cf9fc58ba6f57138e6c",
          "md5": "3744304388911975a98bc8e1472ee5f7"
        }
      ]
    }
  ]
}
